### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by ahmadbilaldev** [santhalakshminarayana/santhalakshminarayana.github.io#1]
In version [3.0](https://github.com/hashicorp/next-mdx-remote/releases/tag/3.0.0), mdx-remote has replaced render-to-string and hydrate with serialize and `<MDXRemote />`.

**Comment by santhalakshminarayana** [comment]
Thank you @ahmadbilaldev, I will look about the changes and update.

**Comment by santhalakshminarayana** [comment]
@ahmadbilaldev 
I have replaced **render-to-string** with **serialize** and **hydrate** with **MDXRemote**. Also it was easy to integrate KaTex in MDX with **serialize**. Thank you.
